<?php

namespace App\Console\Commands;

use Illuminate\Console\Command;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;

class SetupAircraftWtc extends Command
{
    protected $signature = 'aircraft:setup-wtc {--fresh : Drop and recreate the table}';
    protected $description = 'Create aircraft_types_wtc table and seed EASA RECAT-EU data (Issue 2021-12)';

    public function handle(): int
    {
        if ($this->option('fresh') && Schema::hasTable('aircraft_types_wtc')) {
            Schema::drop('aircraft_types_wtc');
            $this->info('Dropped existing aircraft_types_wtc table.');
        }

        if (!Schema::hasTable('aircraft_types_wtc')) {
            Schema::create('aircraft_types_wtc', function (Blueprint $table) {
                $table->id();
                $table->string('manufacturer', 100);
                $table->string('model', 150);
                $table->string('icao_type_designator', 20)->index();
                $table->string('icao_legacy_wtc', 10)->nullable();
                $table->string('recat_eu_wtc', 20)->nullable();
                $table->enum('aircraft_class', ['landplane', 'helicopter'])->default('landplane');
                $table->timestamps();
            });
            $this->info('Created aircraft_types_wtc table.');
        } else {
            $this->info('Table aircraft_types_wtc already exists. Use --fresh to recreate.');
        }

        $existing = DB::table('aircraft_types_wtc')->count();
        if ($existing > 0 && !$this->option('fresh')) {
            $this->warn("Table already has {$existing} records. Use --fresh to reseed.");
            return self::SUCCESS;
        }

        $this->info('Seeding landplane aircraft...');
        $bar = $this->output->createProgressBar(count($this->landplanes()));
        $bar->start();

        foreach (array_chunk($this->landplanes(), 200) as $chunk) {
            $rows = array_map(fn($r) => array_merge($r, [
                'aircraft_class' => 'landplane',
                'created_at' => now(),
                'updated_at' => now(),
            ]), $chunk);
            DB::table('aircraft_types_wtc')->insert($rows);
            $bar->advance(count($chunk));
        }
        $bar->finish();
        $this->newLine();

        $this->info('Seeding helicopter aircraft...');
        $bar2 = $this->output->createProgressBar(count($this->helicopters()));
        $bar2->start();

        foreach (array_chunk($this->helicopters(), 200) as $chunk) {
            $rows = array_map(fn($r) => array_merge($r, [
                'aircraft_class' => 'helicopter',
                'created_at' => now(),
                'updated_at' => now(),
            ]), $chunk);
            DB::table('aircraft_types_wtc')->insert($rows);
            $bar2->advance(count($chunk));
        }
        $bar2->finish();
        $this->newLine();

        $total = DB::table('aircraft_types_wtc')->count();
        $this->info("Done! Total records inserted: {$total}");
        return self::SUCCESS;
    }

    private function landplanes(): array
    {
        return [
            ['manufacturer'=>'DOUGLAS','model'=>'AD Skyraider','icao_type_designator'=>'A1','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-F'],
            ['manufacturer'=>'FAIRCHILD','model'=>'A-10 Thunderbolt 2','icao_type_designator'=>'A10','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-E'],
            ['manufacturer'=>'AEROTEC','model'=>'A-122 Uirapuru','icao_type_designator'=>'A122','icao_legacy_wtc'=>'L','recat_eu_wtc'=>'CAT-F'],
            ['manufacturer'=>'ANTONOV','model'=>'An-124 Ruslan','icao_type_designator'=>'A124','icao_legacy_wtc'=>'H','recat_eu_wtc'=>'CAT-A'],
            ['manufacturer'=>'HESA','model'=>'IRAN-140 Faraz','icao_type_designator'=>'A140','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-E'],
            ['manufacturer'=>'ANTONOV','model'=>'An-148','icao_type_designator'=>'A148','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-E'],
            ['manufacturer'=>'ANTONOV','model'=>'An-158','icao_type_designator'=>'A158','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'TBC'],
            ['manufacturer'=>'AVIADESIGN','model'=>'A-16 Sport Falcon','icao_type_designator'=>'A16','icao_legacy_wtc'=>'L','recat_eu_wtc'=>'CAT-F'],
            ['manufacturer'=>'ANTONOV','model'=>'An-178','icao_type_designator'=>'A178','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-E'],
            ['manufacturer'=>'AEROPRACT','model'=>'A-19','icao_type_designator'=>'A19','icao_legacy_wtc'=>'L','recat_eu_wtc'=>'CAT-F'],
            ['manufacturer'=>'AIRBUS','model'=>'A319NEO','icao_type_designator'=>'A19N','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-D'],
            ['manufacturer'=>'DOUGLAS','model'=>'A-20 Havoc','icao_type_designator'=>'A20','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-F'],
            ['manufacturer'=>'SCHLEICHER','model'=>'ASW-20J','icao_type_designator'=>'A20J','icao_legacy_wtc'=>'L','recat_eu_wtc'=>'CAT-F'],
            ['manufacturer'=>'AIRBUS','model'=>'A320NEO','icao_type_designator'=>'A20N','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-D'],
            ['manufacturer'=>'AEROPRACT','model'=>'A-21 Solo','icao_type_designator'=>'A21','icao_legacy_wtc'=>'L','recat_eu_wtc'=>'CAT-F'],
            ['manufacturer'=>'AQUILA','model'=>'A-210','icao_type_designator'=>'A210','icao_legacy_wtc'=>'L','recat_eu_wtc'=>'CAT-F'],
            ['manufacturer'=>'ALFA-M','model'=>'A-211','icao_type_designator'=>'A211','icao_legacy_wtc'=>'L','recat_eu_wtc'=>'CAT-F'],
            ['manufacturer'=>'AIRBUS','model'=>'A321NEO','icao_type_designator'=>'A21N','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-D'],
            ['manufacturer'=>'SADLER','model'=>'Piranha','icao_type_designator'=>'A22','icao_legacy_wtc'=>'L','recat_eu_wtc'=>'CAT-F'],
            ['manufacturer'=>'OSKBES-MAI','model'=>'Kityonok','icao_type_designator'=>'A223','icao_legacy_wtc'=>'L','recat_eu_wtc'=>'CAT-F'],
            ['manufacturer'=>'ANTONOV','model'=>'Mriya','icao_type_designator'=>'A225','icao_legacy_wtc'=>'H','recat_eu_wtc'=>'Special'],
            ['manufacturer'=>'AEROPRACT','model'=>'A-23 Dragon','icao_type_designator'=>'A23','icao_legacy_wtc'=>'L','recat_eu_wtc'=>'CAT-F'],
            ['manufacturer'=>'AVANTAGE','model'=>'A-27','icao_type_designator'=>'A27','icao_legacy_wtc'=>'L','recat_eu_wtc'=>'CAT-F'],
            ['manufacturer'=>'IBIS','model'=>'Ae-270 Ibis','icao_type_designator'=>'A270','icao_legacy_wtc'=>'L','recat_eu_wtc'=>'CAT-F'],
            ['manufacturer'=>'AVANTAGE','model'=>'A-29','icao_type_designator'=>'A29','icao_legacy_wtc'=>'L','recat_eu_wtc'=>'CAT-F'],
            ['manufacturer'=>'DOUGLAS','model'=>'A-3 Skywarrior','icao_type_designator'=>'A3','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-E'],
            ['manufacturer'=>'AIRBUS','model'=>'A-300B4-600','icao_type_designator'=>'A306','icao_legacy_wtc'=>'H','recat_eu_wtc'=>'CAT-C'],
            ['manufacturer'=>'AIRBUS','model'=>'A-300B2-1','icao_type_designator'=>'A30B','icao_legacy_wtc'=>'H','recat_eu_wtc'=>'CAT-C'],
            ['manufacturer'=>'AVANTAGE','model'=>'Spectrum','icao_type_designator'=>'A31','icao_legacy_wtc'=>'L','recat_eu_wtc'=>'CAT-F'],
            ['manufacturer'=>'AIRBUS','model'=>'A-310','icao_type_designator'=>'A310','icao_legacy_wtc'=>'H','recat_eu_wtc'=>'CAT-C'],
            ['manufacturer'=>'AIRBUS','model'=>'A-318','icao_type_designator'=>'A318','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-D'],
            ['manufacturer'=>'AIRBUS','model'=>'A-319','icao_type_designator'=>'A319','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-D'],
            ['manufacturer'=>'AIRBUS','model'=>'A-320','icao_type_designator'=>'A320','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-D'],
            ['manufacturer'=>'AIRBUS','model'=>'A-321','icao_type_designator'=>'A321','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-D'],
            ['manufacturer'=>'AEROPRACT','model'=>'A-33','icao_type_designator'=>'A33','icao_legacy_wtc'=>'L','recat_eu_wtc'=>'CAT-F'],
            ['manufacturer'=>'AIRBUS','model'=>'A-330-200','icao_type_designator'=>'A332','icao_legacy_wtc'=>'H','recat_eu_wtc'=>'CAT-B'],
            ['manufacturer'=>'AIRBUS','model'=>'A-330-300','icao_type_designator'=>'A333','icao_legacy_wtc'=>'H','recat_eu_wtc'=>'CAT-B'],
            ['manufacturer'=>'AIRBUS','model'=>'A330-700 Beluga XL','icao_type_designator'=>'A337','icao_legacy_wtc'=>'H','recat_eu_wtc'=>'CAT-B'],
            ['manufacturer'=>'AIRBUS','model'=>'A-330-800','icao_type_designator'=>'A338','icao_legacy_wtc'=>'H','recat_eu_wtc'=>'CAT-B'],
            ['manufacturer'=>'AIRBUS','model'=>'A-330-900','icao_type_designator'=>'A339','icao_legacy_wtc'=>'H','recat_eu_wtc'=>'CAT-B'],
            ['manufacturer'=>'SCHLEICHER','model'=>'AS-33Me','icao_type_designator'=>'A33E','icao_legacy_wtc'=>'L','recat_eu_wtc'=>'CAT-F'],
            ['manufacturer'=>'SCHLEICHER','model'=>'AS-33Es','icao_type_designator'=>'A33P','icao_legacy_wtc'=>'L','recat_eu_wtc'=>'CAT-F'],
            ['manufacturer'=>'AIRBUS','model'=>'A-340-200','icao_type_designator'=>'A342','icao_legacy_wtc'=>'H','recat_eu_wtc'=>'CAT-B'],
            ['manufacturer'=>'AIRBUS','model'=>'A-340-300','icao_type_designator'=>'A343','icao_legacy_wtc'=>'H','recat_eu_wtc'=>'CAT-B'],
            ['manufacturer'=>'AIRBUS','model'=>'A-340-500','icao_type_designator'=>'A345','icao_legacy_wtc'=>'H','recat_eu_wtc'=>'CAT-B'],
            ['manufacturer'=>'AIRBUS','model'=>'A-340-600','icao_type_designator'=>'A346','icao_legacy_wtc'=>'H','recat_eu_wtc'=>'CAT-B'],
            ['manufacturer'=>'SCHLEICHER','model'=>'AS-34Me','icao_type_designator'=>'A34E','icao_legacy_wtc'=>'L','recat_eu_wtc'=>'CAT-F'],
            ['manufacturer'=>'AVANTAGE','model'=>'Scanner','icao_type_designator'=>'A35','icao_legacy_wtc'=>'L','recat_eu_wtc'=>'CAT-F'],
            ['manufacturer'=>'AIRBUS','model'=>'A-350-900 XWB','icao_type_designator'=>'A359','icao_legacy_wtc'=>'H','recat_eu_wtc'=>'CAT-B'],
            ['manufacturer'=>'AIRBUS','model'=>'A-350-1000 XWB','icao_type_designator'=>'A35K','icao_legacy_wtc'=>'H','recat_eu_wtc'=>'CAT-B'],
            ['manufacturer'=>'CESSNA','model'=>'A-37 Dragonfly','icao_type_designator'=>'A37','icao_legacy_wtc'=>'L','recat_eu_wtc'=>'CAT-F'],
            ['manufacturer'=>'AIRBUS','model'=>'A-380-800','icao_type_designator'=>'A388','icao_legacy_wtc'=>'J','recat_eu_wtc'=>'CAT-A'],
            ['manufacturer'=>'SATIC','model'=>'A-300ST Beluga','icao_type_designator'=>'A3ST','icao_legacy_wtc'=>'H','recat_eu_wtc'=>'CAT-C'],
            ['manufacturer'=>'SINGAPORE','model'=>'A-4 Super Skyhawk','icao_type_designator'=>'A4','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-F'],
            ['manufacturer'=>'AIRBUS','model'=>'A-400M Grizzly','icao_type_designator'=>'A400','icao_legacy_wtc'=>'H','recat_eu_wtc'=>'CAT-C'],
            ['manufacturer'=>'ILYUSHIN','model'=>'Be-976','icao_type_designator'=>'A50','icao_legacy_wtc'=>'H','recat_eu_wtc'=>'CAT-C'],
            ['manufacturer'=>'ADAM','model'=>'CarbonAero','icao_type_designator'=>'A500','icao_legacy_wtc'=>'L','recat_eu_wtc'=>'CAT-F'],
            ['manufacturer'=>'AVRO','model'=>'504','icao_type_designator'=>'A504','icao_legacy_wtc'=>'L','recat_eu_wtc'=>'CAT-F'],
            ['manufacturer'=>'GRUMMAN','model'=>'A-6 Intruder','icao_type_designator'=>'A6','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-E'],
            ['manufacturer'=>'THRUSH','model'=>'Turbo Thrush 660','icao_type_designator'=>'A660','icao_legacy_wtc'=>'L','recat_eu_wtc'=>'CAT-F'],
            ['manufacturer'=>'ADAM','model'=>'AdamJet','icao_type_designator'=>'A700','icao_legacy_wtc'=>'L','recat_eu_wtc'=>'CAT-F'],
            ['manufacturer'=>'ANTONOV','model'=>'An-74-300','icao_type_designator'=>'A743','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-E'],
            ['manufacturer'=>'BRITISH AEROSPACE','model'=>'Bae-748','icao_type_designator'=>'A748','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-E'],
            ['manufacturer'=>'OSKBES-MAI','model'=>'MAI-890','icao_type_designator'=>'A890','icao_legacy_wtc'=>'L','recat_eu_wtc'=>'CAT-F'],
            ['manufacturer'=>'NORTH AMERICAN ROCKWELL','model'=>'A-9 Sparrow Commander','icao_type_designator'=>'A9','icao_legacy_wtc'=>'L','recat_eu_wtc'=>'CAT-F'],
            ['manufacturer'=>'OSKBES-MAI','model'=>'Acrobat','icao_type_designator'=>'A900','icao_legacy_wtc'=>'L','recat_eu_wtc'=>'CAT-F'],
            ['manufacturer'=>'OSKBES-MAI','model'=>'MAI-960 Interfly','icao_type_designator'=>'A910','icao_legacy_wtc'=>'L','recat_eu_wtc'=>'CAT-F'],
            ['manufacturer'=>'GULFSTREAM AMERICAN','model'=>'AA-1 T-Cat','icao_type_designator'=>'AA1','icao_legacy_wtc'=>'L','recat_eu_wtc'=>'CAT-F'],
            ['manufacturer'=>'AEROPRACT','model'=>'A-37','icao_type_designator'=>'AA37','icao_legacy_wtc'=>'L','recat_eu_wtc'=>'CAT-F'],
            ['manufacturer'=>'TIGER','model'=>'AG-5 Tiger','icao_type_designator'=>'AA5','icao_legacy_wtc'=>'L','recat_eu_wtc'=>'CAT-F'],
            ['manufacturer'=>'AERO','model'=>'AT-3','icao_type_designator'=>'AAT3','icao_legacy_wtc'=>'L','recat_eu_wtc'=>'CAT-F'],
            ['manufacturer'=>'GOBOSH','model'=>'G-700','icao_type_designator'=>'AAT4','icao_legacy_wtc'=>'L','recat_eu_wtc'=>'CAT-F'],
            ['manufacturer'=>'AERO BOERO','model'=>'AB-115','icao_type_designator'=>'AB11','icao_legacy_wtc'=>'L','recat_eu_wtc'=>'CAT-F'],
            ['manufacturer'=>'AERO BOERO','model'=>'AB-150','icao_type_designator'=>'AB15','icao_legacy_wtc'=>'L','recat_eu_wtc'=>'CAT-F'],
            ['manufacturer'=>'AERO BOERO','model'=>'AB-180','icao_type_designator'=>'AB18','icao_legacy_wtc'=>'L','recat_eu_wtc'=>'CAT-F'],
            ['manufacturer'=>'AERO BOERO','model'=>'AB-95','icao_type_designator'=>'AB95','icao_legacy_wtc'=>'L','recat_eu_wtc'=>'CAT-F'],
            ['manufacturer'=>'ROCKWELL','model'=>'112 Alpine Commander','icao_type_designator'=>'AC11','icao_legacy_wtc'=>'L','recat_eu_wtc'=>'CAT-F'],
            ['manufacturer'=>'LIGHT WING','model'=>'AC-4','icao_type_designator'=>'AC4','icao_legacy_wtc'=>'L','recat_eu_wtc'=>'CAT-F'],
            ['manufacturer'=>'ROCKWELL','model'=>'500 Shrike Commander','icao_type_designator'=>'AC50','icao_legacy_wtc'=>'L','recat_eu_wtc'=>'CAT-F'],
            ['manufacturer'=>'AERO','model'=>'Commander 520','icao_type_designator'=>'AC52','icao_legacy_wtc'=>'L','recat_eu_wtc'=>'CAT-F'],
            ['manufacturer'=>'AERO COMMANDER','model'=>'Commander 560','icao_type_designator'=>'AC56','icao_legacy_wtc'=>'L','recat_eu_wtc'=>'CAT-F'],
            ['manufacturer'=>'NANJING','model'=>'Aircar','icao_type_designator'=>'AC5A','icao_legacy_wtc'=>'L','recat_eu_wtc'=>'CAT-F'],
            ['manufacturer'=>'AVIASTROITEL','model'=>'AC-5M','icao_type_designator'=>'AC5M','icao_legacy_wtc'=>'L','recat_eu_wtc'=>'CAT-F'],
            ['manufacturer'=>'AERO COMMANDER','model'=>'Commander 680FP','icao_type_designator'=>'AC68','icao_legacy_wtc'=>'L','recat_eu_wtc'=>'CAT-F'],
            ['manufacturer'=>'ROCKWELL','model'=>'Commander 685','icao_type_designator'=>'AC6L','icao_legacy_wtc'=>'L','recat_eu_wtc'=>'CAT-F'],
            ['manufacturer'=>'AERO COMMANDER','model'=>'Alti Cruiser','icao_type_designator'=>'AC72','icao_legacy_wtc'=>'L','recat_eu_wtc'=>'CAT-F'],
            ['manufacturer'=>'NORTH AMERICAN ROCKWELL','model'=>'680W Turbo 2 Commander','icao_type_designator'=>'AC80','icao_legacy_wtc'=>'L','recat_eu_wtc'=>'CAT-F'],
            ['manufacturer'=>'ROCKWELL','model'=>'Jetprop Commander 840','icao_type_designator'=>'AC90','icao_legacy_wtc'=>'L','recat_eu_wtc'=>'CAT-F'],
            ['manufacturer'=>'ROCKWELL','model'=>'Jetprop Commander 980','icao_type_designator'=>'AC95','icao_legacy_wtc'=>'L','recat_eu_wtc'=>'CAT-F'],
            ['manufacturer'=>'LOCKWOOD','model'=>'Air Cam','icao_type_designator'=>'ACAM','icao_legacy_wtc'=>'L','recat_eu_wtc'=>'CAT-F'],
            ['manufacturer'=>'AUSTER','model'=>'Autocar','icao_type_designator'=>'ACAR','icao_legacy_wtc'=>'L','recat_eu_wtc'=>'CAT-F'],
            ['manufacturer'=>'POWELL','model'=>'P-70 Acey Deucy','icao_type_designator'=>'ACED','icao_legacy_wtc'=>'L','recat_eu_wtc'=>'CAT-F'],
            ['manufacturer'=>'OPTION AIR','model'=>'Acapella','icao_type_designator'=>'ACPL','icao_legacy_wtc'=>'L','recat_eu_wtc'=>'CAT-F'],
            ['manufacturer'=>'EAA','model'=>'Acro-Sport 2','icao_type_designator'=>'ACR2','icao_legacy_wtc'=>'L','recat_eu_wtc'=>'CAT-F'],
            ['manufacturer'=>'AVIA','model'=>'Accord','icao_type_designator'=>'ACRD','icao_legacy_wtc'=>'L','recat_eu_wtc'=>'CAT-F'],
            ['manufacturer'=>'EAA','model'=>'Super Acro-Sport','icao_type_designator'=>'ACRO','icao_legacy_wtc'=>'L','recat_eu_wtc'=>'CAT-F'],
            ['manufacturer'=>'VICTA','model'=>'Aircruiser','icao_type_designator'=>'ACSR','icao_legacy_wtc'=>'L','recat_eu_wtc'=>'CAT-F'],
            ['manufacturer'=>'CAIGA','model'=>'AG-600 Kunlong','icao_type_designator'=>'AG60','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-D'],
            ['manufacturer'=>'COMAC','model'=>'ARJ-21-700 Xiangfeng','icao_type_designator'=>'AJ27','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-E'],
            ['manufacturer'=>'DORNIER','model'=>'Alpha Jet','icao_type_designator'=>'AJET','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-F'],
            ['manufacturer'=>'ANTONOV','model'=>'An-26','icao_type_designator'=>'AN26','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-E'],
            ['manufacturer'=>'PZL-MIELEC','model'=>'An-28','icao_type_designator'=>'AN28','icao_legacy_wtc'=>'L','recat_eu_wtc'=>'CAT-F'],
            ['manufacturer'=>'ANTONOV','model'=>'An-3','icao_type_designator'=>'AN3','icao_legacy_wtc'=>'L','recat_eu_wtc'=>'CAT-F'],
            ['manufacturer'=>'ANTONOV','model'=>'An-30','icao_type_designator'=>'AN30','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-E'],
            ['manufacturer'=>'ANTONOV','model'=>'An-32','icao_type_designator'=>'AN32','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-E'],
            ['manufacturer'=>'ANTONOV','model'=>'An-38','icao_type_designator'=>'AN38','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-F'],
            ['manufacturer'=>'ANTONOV','model'=>'An-70','icao_type_designator'=>'AN70','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-C'],
            ['manufacturer'=>'ANTONOV','model'=>'An-72','icao_type_designator'=>'AN72','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-E'],
            ['manufacturer'=>'ANTONOV','model'=>'An-8','icao_type_designator'=>'AN8','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-D'],
            ['manufacturer'=>'ANTONOV','model'=>'An-12','icao_type_designator'=>'AN12','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-D'],
            ['manufacturer'=>'ANTONOV','model'=>'An-2','icao_type_designator'=>'AN2','icao_legacy_wtc'=>'L','recat_eu_wtc'=>'CAT-F'],
            ['manufacturer'=>'ANTONOV','model'=>'An-22 Antheus','icao_type_designator'=>'AN22','icao_legacy_wtc'=>'H','recat_eu_wtc'=>'CAT-B'],
            ['manufacturer'=>'ANTONOV','model'=>'An-24','icao_type_designator'=>'AN24','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-E'],
            ['manufacturer'=>'ATR','model'=>'ATR-42-300','icao_type_designator'=>'AT43','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-E'],
            ['manufacturer'=>'ATR','model'=>'ATR-42-400','icao_type_designator'=>'AT44','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-E'],
            ['manufacturer'=>'ATR','model'=>'ATR-42-500','icao_type_designator'=>'AT45','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-E'],
            ['manufacturer'=>'ATR','model'=>'ATR-42-600','icao_type_designator'=>'AT46','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-E'],
            ['manufacturer'=>'ATR','model'=>'ATR-72-201','icao_type_designator'=>'AT72','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-E'],
            ['manufacturer'=>'ATR','model'=>'ATR-72-211','icao_type_designator'=>'AT73','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-E'],
            ['manufacturer'=>'ATR','model'=>'ATR-72-500','icao_type_designator'=>'AT75','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-E'],
            ['manufacturer'=>'ATR','model'=>'ATR-72-600','icao_type_designator'=>'AT76','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-E'],
            ['manufacturer'=>'BRITISH AEROSPACE','model'=>'ATP','icao_type_designator'=>'ATP','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-E'],
            ['manufacturer'=>'BOEING','model'=>'B-17 Flying Fortress','icao_type_designator'=>'B17','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-E'],
            ['manufacturer'=>'BEECH','model'=>'1900','icao_type_designator'=>'B190','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-F'],
            ['manufacturer'=>'BOEING','model'=>'737 MAX -7','icao_type_designator'=>'B37M','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-D'],
            ['manufacturer'=>'BOEING','model'=>'737 MAX -8','icao_type_designator'=>'B38M','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-D'],
            ['manufacturer'=>'BOEING','model'=>'737 MAX -9','icao_type_designator'=>'B39M','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-D'],
            ['manufacturer'=>'BOEING','model'=>'737 MAX 10','icao_type_designator'=>'B3XM','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-D'],
            ['manufacturer'=>'BRITISH AEROSPACE','model'=>'BAe-146-100','icao_type_designator'=>'B461','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-E'],
            ['manufacturer'=>'BRITISH AEROSPACE','model'=>'BAe-146-200','icao_type_designator'=>'B462','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-E'],
            ['manufacturer'=>'BRITISH AEROSPACE','model'=>'BAe-146-300','icao_type_designator'=>'B463','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-E'],
            ['manufacturer'=>'BOEING','model'=>'707-100','icao_type_designator'=>'B701','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-C'],
            ['manufacturer'=>'BOEING','model'=>'707-300','icao_type_designator'=>'B703','icao_legacy_wtc'=>'H','recat_eu_wtc'=>'CAT-C'],
            ['manufacturer'=>'BOEING','model'=>'717-200','icao_type_designator'=>'B712','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-E'],
            ['manufacturer'=>'BOEING','model'=>'720','icao_type_designator'=>'B720','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-C'],
            ['manufacturer'=>'BOEING','model'=>'727-100','icao_type_designator'=>'B721','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-D'],
            ['manufacturer'=>'BOEING','model'=>'727-200','icao_type_designator'=>'B722','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-D'],
            ['manufacturer'=>'BOEING','model'=>'737-200','icao_type_designator'=>'B732','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-E'],
            ['manufacturer'=>'BOEING','model'=>'737-300','icao_type_designator'=>'B733','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-E'],
            ['manufacturer'=>'BOEING','model'=>'737-400','icao_type_designator'=>'B734','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-E'],
            ['manufacturer'=>'BOEING','model'=>'737-500','icao_type_designator'=>'B735','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-E'],
            ['manufacturer'=>'BOEING','model'=>'737-600','icao_type_designator'=>'B736','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-D'],
            ['manufacturer'=>'BOEING','model'=>'737-700','icao_type_designator'=>'B737','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-D'],
            ['manufacturer'=>'BOEING','model'=>'737-800','icao_type_designator'=>'B738','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-D'],
            ['manufacturer'=>'BOEING','model'=>'737-900','icao_type_designator'=>'B739','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-D'],
            ['manufacturer'=>'BOEING','model'=>'747-100','icao_type_designator'=>'B741','icao_legacy_wtc'=>'H','recat_eu_wtc'=>'CAT-B'],
            ['manufacturer'=>'BOEING','model'=>'747-200','icao_type_designator'=>'B742','icao_legacy_wtc'=>'H','recat_eu_wtc'=>'CAT-B'],
            ['manufacturer'=>'BOEING','model'=>'747-300','icao_type_designator'=>'B743','icao_legacy_wtc'=>'H','recat_eu_wtc'=>'CAT-B'],
            ['manufacturer'=>'BOEING','model'=>'747-400','icao_type_designator'=>'B744','icao_legacy_wtc'=>'H','recat_eu_wtc'=>'CAT-B'],
            ['manufacturer'=>'BOEING','model'=>'747-8','icao_type_designator'=>'B748','icao_legacy_wtc'=>'H','recat_eu_wtc'=>'CAT-B'],
            ['manufacturer'=>'BOEING','model'=>'747SR','icao_type_designator'=>'B74R','icao_legacy_wtc'=>'H','recat_eu_wtc'=>'CAT-B'],
            ['manufacturer'=>'BOEING','model'=>'747SP','icao_type_designator'=>'B74S','icao_legacy_wtc'=>'H','recat_eu_wtc'=>'CAT-B'],
            ['manufacturer'=>'BOEING','model'=>'747-400LCF Dreamlifter','icao_type_designator'=>'BLCF','icao_legacy_wtc'=>'H','recat_eu_wtc'=>'CAT-B'],
            ['manufacturer'=>'BOEING','model'=>'757-200','icao_type_designator'=>'B752','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-C'],
            ['manufacturer'=>'BOEING','model'=>'757-300','icao_type_designator'=>'B753','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-C'],
            ['manufacturer'=>'BOEING','model'=>'767-200','icao_type_designator'=>'B762','icao_legacy_wtc'=>'H','recat_eu_wtc'=>'CAT-C'],
            ['manufacturer'=>'BOEING','model'=>'767-300','icao_type_designator'=>'B763','icao_legacy_wtc'=>'H','recat_eu_wtc'=>'CAT-C'],
            ['manufacturer'=>'BOEING','model'=>'767-400','icao_type_designator'=>'B764','icao_legacy_wtc'=>'H','recat_eu_wtc'=>'CAT-C'],
            ['manufacturer'=>'BOEING','model'=>'777-200ER','icao_type_designator'=>'B772','icao_legacy_wtc'=>'H','recat_eu_wtc'=>'CAT-B'],
            ['manufacturer'=>'BOEING','model'=>'777-300','icao_type_designator'=>'B773','icao_legacy_wtc'=>'H','recat_eu_wtc'=>'CAT-B'],
            ['manufacturer'=>'BOEING','model'=>'777-8','icao_type_designator'=>'B778','icao_legacy_wtc'=>'H','recat_eu_wtc'=>'CAT-B'],
            ['manufacturer'=>'BOEING','model'=>'777-9','icao_type_designator'=>'B779','icao_legacy_wtc'=>'H','recat_eu_wtc'=>'CAT-B'],
            ['manufacturer'=>'BOEING','model'=>'777-200LR','icao_type_designator'=>'B77L','icao_legacy_wtc'=>'H','recat_eu_wtc'=>'CAT-B'],
            ['manufacturer'=>'BOEING','model'=>'777-300ER','icao_type_designator'=>'B77W','icao_legacy_wtc'=>'H','recat_eu_wtc'=>'CAT-B'],
            ['manufacturer'=>'BOEING','model'=>'787-8 Dreamliner','icao_type_designator'=>'B788','icao_legacy_wtc'=>'H','recat_eu_wtc'=>'CAT-B'],
            ['manufacturer'=>'BOEING','model'=>'787-9 Dreamliner','icao_type_designator'=>'B789','icao_legacy_wtc'=>'H','recat_eu_wtc'=>'CAT-B'],
            ['manufacturer'=>'BOEING','model'=>'787-10 Dreamliner','icao_type_designator'=>'B78X','icao_legacy_wtc'=>'H','recat_eu_wtc'=>'CAT-B'],
            ['manufacturer'=>'BRITISH AEROSPACE','model'=>'One-Eleven','icao_type_designator'=>'BA11','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-E'],
            ['manufacturer'=>'AIRBUS','model'=>'A-220-100','icao_type_designator'=>'BCS1','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-D'],
            ['manufacturer'=>'AIRBUS','model'=>'A-220-300','icao_type_designator'=>'BCS3','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-D'],
            ['manufacturer'=>'BEECH','model'=>'200 Super King Air','icao_type_designator'=>'BE20','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-F'],
            ['manufacturer'=>'BEECH','model'=>'400 Beechjet','icao_type_designator'=>'BE40','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-F'],
            ['manufacturer'=>'BEECH','model'=>'400XPR','icao_type_designator'=>'BE4W','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-F'],
            ['manufacturer'=>'SHORT','model'=>'SC-5 Belfast','icao_type_designator'=>'BELF','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-C'],
            ['manufacturer'=>'BOEING','model'=>'C-135 Stratolifter','icao_type_designator'=>'C135','icao_legacy_wtc'=>'H','recat_eu_wtc'=>'CAT-C'],
            ['manufacturer'=>'LOCKHEED','model'=>'C-141 Starlifter','icao_type_designator'=>'C141','icao_legacy_wtc'=>'H','recat_eu_wtc'=>'CAT-C'],
            ['manufacturer'=>'LOCKHEED','model'=>'C-130 Hercules','icao_type_designator'=>'C130','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-D'],
            ['manufacturer'=>'CESSNA','model'=>'208 Caravan 1','icao_type_designator'=>'C208','icao_legacy_wtc'=>'L','recat_eu_wtc'=>'CAT-F'],
            ['manufacturer'=>'CASA','model'=>'C-212 Aviocar','icao_type_designator'=>'C212','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-F'],
            ['manufacturer'=>'CESSNA','model'=>'525A Citation CJ2','icao_type_designator'=>'C25A','icao_legacy_wtc'=>'L','recat_eu_wtc'=>'CAT-F'],
            ['manufacturer'=>'CESSNA','model'=>'525B Citation CJ3','icao_type_designator'=>'C25B','icao_legacy_wtc'=>'L','recat_eu_wtc'=>'CAT-F'],
            ['manufacturer'=>'CESSNA','model'=>'525C Citation CJ4','icao_type_designator'=>'C25C','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-F'],
            ['manufacturer'=>'ALENIA AERMACCHI','model'=>'C-27J Spartan','icao_type_designator'=>'C27J','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-E'],
            ['manufacturer'=>'CASA','model'=>'C-295','icao_type_designator'=>'C295','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-E'],
            ['manufacturer'=>'LOCKHEED MARTIN','model'=>'C-130J Hercules','icao_type_designator'=>'C30J','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-D'],
            ['manufacturer'=>'LOCKHEED','model'=>'C-5M Super Galaxy','icao_type_designator'=>'C5M','icao_legacy_wtc'=>'H','recat_eu_wtc'=>'TBC'],
            ['manufacturer'=>'CESSNA','model'=>'700 Citation Longitude','icao_type_designator'=>'C700','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-E'],
            ['manufacturer'=>'CESSNA','model'=>'750 Citation 10','icao_type_designator'=>'C750','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-E'],
            ['manufacturer'=>'COMAC','model'=>'C-919','icao_type_designator'=>'C919','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-D'],
            ['manufacturer'=>'CANADAIR','model'=>'Regional Jet CRJ-100','icao_type_designator'=>'CRJ1','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-E'],
            ['manufacturer'=>'CANADAIR','model'=>'Regional Jet CRJ-200','icao_type_designator'=>'CRJ2','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-E'],
            ['manufacturer'=>'CANADAIR','model'=>'Regional Jet CRJ-700','icao_type_designator'=>'CRJ7','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-E'],
            ['manufacturer'=>'CANADAIR','model'=>'Regional Jet CRJ-900','icao_type_designator'=>'CRJ9','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-E'],
            ['manufacturer'=>'BOMBARDIER','model'=>'Regional Jet CRJ-1000','icao_type_designator'=>'CRJX','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-E'],
            ['manufacturer'=>'BOMBARDIER','model'=>'Challenger 300','icao_type_designator'=>'CL30','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-E'],
            ['manufacturer'=>'BOMBARDIER','model'=>'Challenger 350','icao_type_designator'=>'CL35','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-E'],
            ['manufacturer'=>'CANADAIR','model'=>'CL-600 Challenger 600','icao_type_designator'=>'CL60','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-E'],
            ['manufacturer'=>'CASA','model'=>'CN-235','icao_type_designator'=>'CN35','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-E'],
            ['manufacturer'=>'DE HAVILLAND CANADA','model'=>'DHC-8-100 Dash 8','icao_type_designator'=>'DH8A','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-E'],
            ['manufacturer'=>'DE HAVILLAND CANADA','model'=>'DHC-8-200 Dash 8','icao_type_designator'=>'DH8B','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-E'],
            ['manufacturer'=>'DE HAVILLAND CANADA','model'=>'DHC-8-300 Dash 8','icao_type_designator'=>'DH8C','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-E'],
            ['manufacturer'=>'DE HAVILLAND CANADA','model'=>'DHC-8-400 Dash 8','icao_type_designator'=>'DH8D','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-E'],
            ['manufacturer'=>'DE HAVILLAND CANADA','model'=>'DHC-5 Buffalo','icao_type_designator'=>'DHC5','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-E'],
            ['manufacturer'=>'DE HAVILLAND CANADA','model'=>'DHC-7 Dash 7','icao_type_designator'=>'DHC7','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-E'],
            ['manufacturer'=>'MCDONNELL DOUGLAS','model'=>'Extender','icao_type_designator'=>'DC10','icao_legacy_wtc'=>'H','recat_eu_wtc'=>'CAT-C'],
            ['manufacturer'=>'MCDONNELL DOUGLAS','model'=>'DC-8-50','icao_type_designator'=>'DC85','icao_legacy_wtc'=>'H','recat_eu_wtc'=>'CAT-C'],
            ['manufacturer'=>'MCDONNELL DOUGLAS','model'=>'DC-8-60','icao_type_designator'=>'DC86','icao_legacy_wtc'=>'H','recat_eu_wtc'=>'CAT-C'],
            ['manufacturer'=>'MCDONNELL DOUGLAS','model'=>'DC-8-70','icao_type_designator'=>'DC87','icao_legacy_wtc'=>'H','recat_eu_wtc'=>'CAT-C'],
            ['manufacturer'=>'MCDONNELL DOUGLAS','model'=>'DC-9-10','icao_type_designator'=>'DC91','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-E'],
            ['manufacturer'=>'MCDONNELL DOUGLAS','model'=>'DC-9-20','icao_type_designator'=>'DC92','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-E'],
            ['manufacturer'=>'MCDONNELL DOUGLAS','model'=>'DC-9-30','icao_type_designator'=>'DC93','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-E'],
            ['manufacturer'=>'MCDONNELL DOUGLAS','model'=>'DC-9-40','icao_type_designator'=>'DC94','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-E'],
            ['manufacturer'=>'MCDONNELL DOUGLAS','model'=>'DC-9-50','icao_type_designator'=>'DC95','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-E'],
            ['manufacturer'=>'EMBRAER','model'=>'EMB-135','icao_type_designator'=>'E135','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-E'],
            ['manufacturer'=>'EMBRAER','model'=>'EMB-145','icao_type_designator'=>'E145','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-E'],
            ['manufacturer'=>'EMBRAER','model'=>'EMB-170','icao_type_designator'=>'E170','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-E'],
            ['manufacturer'=>'EMBRAER','model'=>'EMB-190','icao_type_designator'=>'E190','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-E'],
            ['manufacturer'=>'EMBRAER','model'=>'EMB-195','icao_type_designator'=>'E195','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-E'],
            ['manufacturer'=>'EMBRAER','model'=>'E175-E2','icao_type_designator'=>'E275','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'TBC'],
            ['manufacturer'=>'EMBRAER','model'=>'E190-E2','icao_type_designator'=>'E290','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-D'],
            ['manufacturer'=>'EMBRAER','model'=>'E195-E2','icao_type_designator'=>'E295','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-D'],
            ['manufacturer'=>'EMBRAER','model'=>'Legacy 650','icao_type_designator'=>'E35L','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-E'],
            ['manufacturer'=>'EMBRAER','model'=>'EMB-390','icao_type_designator'=>'E390','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-D'],
            ['manufacturer'=>'BOEING','model'=>'E-3A (CFM56) Sentry','icao_type_designator'=>'E3CF','icao_legacy_wtc'=>'H','recat_eu_wtc'=>'CAT-C'],
            ['manufacturer'=>'BOEING','model'=>'E-3B Sentry','icao_type_designator'=>'E3TF','icao_legacy_wtc'=>'H','recat_eu_wtc'=>'CAT-C'],
            ['manufacturer'=>'EMBRAER','model'=>'EMB-145XR','icao_type_designator'=>'E45X','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-E'],
            ['manufacturer'=>'EMBRAER','model'=>'EMB-545 Legacy 450','icao_type_designator'=>'E545','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-E'],
            ['manufacturer'=>'EMBRAER','model'=>'EMB-550 Legacy 500','icao_type_designator'=>'E550','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-E'],
            ['manufacturer'=>'BOEING','model'=>'737-700 Wedgetail','icao_type_designator'=>'E737','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-D'],
            ['manufacturer'=>'EMBRAER','model'=>'EMB-175 (long wing)','icao_type_designator'=>'E75L','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-E'],
            ['manufacturer'=>'EMBRAER','model'=>'EMB-175 (short wing)','icao_type_designator'=>'E75S','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-E'],
            ['manufacturer'=>'BOEING','model'=>'E-767','icao_type_designator'=>'E767','icao_legacy_wtc'=>'H','recat_eu_wtc'=>'CAT-C'],
            ['manufacturer'=>'EUROFIGHTER','model'=>'Typhoon','icao_type_designator'=>'EUFI','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-E'],
            ['manufacturer'=>'FOKKER','model'=>'100','icao_type_designator'=>'F100','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-E'],
            ['manufacturer'=>'CONVAIR','model'=>'QF-106 Delta Dart','icao_type_designator'=>'F106','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-E'],
            ['manufacturer'=>'GENERAL DYNAMICS','model'=>'F-111 Raven','icao_type_designator'=>'F111','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-E'],
            ['manufacturer'=>'GRUMMAN','model'=>'F-14 Tomcat','icao_type_designator'=>'F14','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-E'],
            ['manufacturer'=>'BOEING','model'=>'F-15 Eagle','icao_type_designator'=>'F15','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-E'],
            ['manufacturer'=>'GENERAL DYNAMICS','model'=>'F-16 Fighting Falcon','icao_type_designator'=>'F16','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-E'],
            ['manufacturer'=>'GENERAL DYNAMICS','model'=>'F-16XL Fighting Falcon','icao_type_designator'=>'F16X','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-E'],
            ['manufacturer'=>'BOEING','model'=>'FA-18 Hornet','icao_type_designator'=>'F18H','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-E'],
            ['manufacturer'=>'MCDONNELL DOUGLAS','model'=>'FA-18F Super Hornet','icao_type_designator'=>'F18S','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-E'],
            ['manufacturer'=>'MITSUBISHI','model'=>'F-2','icao_type_designator'=>'F2','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-E'],
            ['manufacturer'=>'LOCKHEED','model'=>'F-22 Raptor','icao_type_designator'=>'F22','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-E'],
            ['manufacturer'=>'FOKKER','model'=>'F-27 Friendship','icao_type_designator'=>'F27','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-E'],
            ['manufacturer'=>'FOKKER','model'=>'F-28 Fellowship','icao_type_designator'=>'F28','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-E'],
            ['manufacturer'=>'DASSAULT','model'=>'Falcon 2000','icao_type_designator'=>'F2TH','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-E'],
            ['manufacturer'=>'LOCKHEED','model'=>'Lightning II (F-35A/C)','icao_type_designator'=>'F35','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-E'],
            ['manufacturer'=>'MCDONNELL DOUGLAS','model'=>'F-4 Phantom 2','icao_type_designator'=>'F4','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-E'],
            ['manufacturer'=>'FOKKER','model'=>'Fokker 50','icao_type_designator'=>'F50','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-E'],
            ['manufacturer'=>'FOKKER','model'=>'60','icao_type_designator'=>'F60','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-E'],
            ['manufacturer'=>'FOKKER','model'=>'70','icao_type_designator'=>'F70','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-E'],
            ['manufacturer'=>'DASSAULT','model'=>'Falcon 900','icao_type_designator'=>'F900','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-E'],
            ['manufacturer'=>'DASSAULT','model'=>'Falcon 50','icao_type_designator'=>'FA50','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-E'],
            ['manufacturer'=>'DASSAULT','model'=>'Falcon 5X','icao_type_designator'=>'FA5X','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-E'],
            ['manufacturer'=>'DASSAULT','model'=>'Falcon 7X','icao_type_designator'=>'FA7X','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-E'],
            ['manufacturer'=>'DASSAULT','model'=>'Falcon 8X','icao_type_designator'=>'FA8X','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-E'],
            ['manufacturer'=>'BOMBARDIER','model'=>'BD-700 Global 5000','icao_type_designator'=>'GL5T','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-E'],
            ['manufacturer'=>'BOMBARDIER','model'=>'BD-700 Global 6000','icao_type_designator'=>'GL6T','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-E'],
            ['manufacturer'=>'BOMBARDIER','model'=>'BD-700 Global 7000/7500/8000','icao_type_designator'=>'GL7T','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-E'],
            ['manufacturer'=>'RAYTHEON','model'=>'Sentinel','icao_type_designator'=>'GLEX','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-E'],
            ['manufacturer'=>'GULFSTREAM AMERICAN','model'=>'G-1159 Gulfstream 2','icao_type_designator'=>'GLF2','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-E'],
            ['manufacturer'=>'GULFSTREAM AMERICAN','model'=>'G-1159A Gulfstream 3','icao_type_designator'=>'GLF3','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-E'],
            ['manufacturer'=>'GULFSTREAM AEROSPACE','model'=>'Gulfstream G400/G450','icao_type_designator'=>'GLF4','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-E'],
            ['manufacturer'=>'GULFSTREAM AEROSPACE','model'=>'Gulfstream G500/G550','icao_type_designator'=>'GLF5','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-E'],
            ['manufacturer'=>'GULFSTREAM AEROSPACE','model'=>'Gulfstream G650','icao_type_designator'=>'GLF6','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-E'],
            ['manufacturer'=>'ALENIA','model'=>'C-27A Spartan','icao_type_designator'=>'G222','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-E'],
            ['manufacturer'=>'IAI','model'=>'Gulfstream G250','icao_type_designator'=>'G250','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-E'],
            ['manufacturer'=>'IAI','model'=>'Gulfstream G280','icao_type_designator'=>'G280','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-E'],
            ['manufacturer'=>'GULFSTREAM AEROSPACE','model'=>'Gulfstream G500 (G-7)','icao_type_designator'=>'GA5C','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-E'],
            ['manufacturer'=>'GULFSTREAM AEROSPACE','model'=>'Gulfstream G600','icao_type_designator'=>'GA6C','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-E'],
            ['manufacturer'=>'GULFSTREAM AEROSPACE','model'=>'Gulfstream G700','icao_type_designator'=>'GA7C','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-E'],
            ['manufacturer'=>'IAI','model'=>'Galaxy','icao_type_designator'=>'GALX','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-E'],
            ['manufacturer'=>'HAWKER BEECHCRAFT','model'=>'4000 Hawker Horizon','icao_type_designator'=>'HA4T','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-E'],
            ['manufacturer'=>'ILYUSHIN','model'=>'Il-114','icao_type_designator'=>'I114','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-E'],
            ['manufacturer'=>'ILYUSHIN','model'=>'Il-14','icao_type_designator'=>'IL14','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-E'],
            ['manufacturer'=>'ILYUSHIN','model'=>'Il-28','icao_type_designator'=>'IL28','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-E'],
            ['manufacturer'=>'ILYUSHIN','model'=>'Il-62','icao_type_designator'=>'IL62','icao_legacy_wtc'=>'H','recat_eu_wtc'=>'CAT-C'],
            ['manufacturer'=>'ILYUSHIN','model'=>'Il-76','icao_type_designator'=>'IL76','icao_legacy_wtc'=>'H','recat_eu_wtc'=>'CAT-C'],
            ['manufacturer'=>'ILYUSHIN','model'=>'Il-86','icao_type_designator'=>'IL86','icao_legacy_wtc'=>'H','recat_eu_wtc'=>'CAT-C'],
            ['manufacturer'=>'ILYUSHIN','model'=>'Il-96','icao_type_designator'=>'IL96','icao_legacy_wtc'=>'H','recat_eu_wtc'=>'CAT-B'],
            ['manufacturer'=>'CHENGDU','model'=>'F-10','icao_type_designator'=>'J10','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-E'],
            ['manufacturer'=>'CHENGDU','model'=>'J-20','icao_type_designator'=>'J20','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-E'],
            ['manufacturer'=>'SHENYANG','model'=>'F-8T','icao_type_designator'=>'J8B','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-E'],
            ['manufacturer'=>'SEPECAT','model'=>'Jaguar','icao_type_designator'=>'JAGR','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-E'],
            ['manufacturer'=>'XIAN','model'=>'JH-7','icao_type_designator'=>'JH7','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-E'],
            ['manufacturer'=>'RUAG','model'=>'Dornier 328 JET Envoy','icao_type_designator'=>'J328','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-E'],
            ['manufacturer'=>'BOEING','model'=>'Stratotanker (TF33 engines)','icao_type_designator'=>'K35E','icao_legacy_wtc'=>'H','recat_eu_wtc'=>'CAT-C'],
            ['manufacturer'=>'BOEING','model'=>'C-135FR Stratotanker','icao_type_designator'=>'K35R','icao_legacy_wtc'=>'H','recat_eu_wtc'=>'CAT-C'],
            ['manufacturer'=>'KAWASAKI','model'=>'XC-2','icao_type_designator'=>'KC2','icao_legacy_wtc'=>'H','recat_eu_wtc'=>'CAT-C'],
            ['manufacturer'=>'BOEING','model'=>'KE-3','icao_type_designator'=>'KE3','icao_legacy_wtc'=>'H','recat_eu_wtc'=>'CAT-C'],
            ['manufacturer'=>'LOCKHEED','model'=>'TriStar','icao_type_designator'=>'L101','icao_legacy_wtc'=>'H','recat_eu_wtc'=>'CAT-C'],
            ['manufacturer'=>'LOCKHEED','model'=>'L-188 Electra','icao_type_designator'=>'L188','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-E'],
            ['manufacturer'=>'AVRO','model'=>'683 Lancaster','icao_type_designator'=>'LANC','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-E'],
            ['manufacturer'=>'ENGLISH ELECTRIC','model'=>'Lightning','icao_type_designator'=>'LTNG','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-E'],
            ['manufacturer'=>'XIAN','model'=>'MA-60','icao_type_designator'=>'MA60','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-E'],
            ['manufacturer'=>'XIAN','model'=>'MA-60H','icao_type_designator'=>'MA6H','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-E'],
            ['manufacturer'=>'MARTIN','model'=>'404','icao_type_designator'=>'M404','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-E'],
            ['manufacturer'=>'ALENIA AERMACCHI','model'=>'M-346 Master','icao_type_designator'=>'M346','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-F'],
            ['manufacturer'=>'MCDONNELL DOUGLAS','model'=>'MD-11','icao_type_designator'=>'MD11','icao_legacy_wtc'=>'H','recat_eu_wtc'=>'CAT-C'],
            ['manufacturer'=>'MCDONNELL DOUGLAS','model'=>'MD-81','icao_type_designator'=>'MD81','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-D'],
            ['manufacturer'=>'MCDONNELL DOUGLAS','model'=>'MD-82','icao_type_designator'=>'MD82','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-D'],
            ['manufacturer'=>'MCDONNELL DOUGLAS','model'=>'MD-83','icao_type_designator'=>'MD83','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-D'],
            ['manufacturer'=>'MCDONNELL DOUGLAS','model'=>'MD-87','icao_type_designator'=>'MD87','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-D'],
            ['manufacturer'=>'MCDONNELL DOUGLAS','model'=>'MD-88','icao_type_designator'=>'MD88','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-D'],
            ['manufacturer'=>'MCDONNELL DOUGLAS','model'=>'MD-90','icao_type_designator'=>'MD90','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-D'],
            ['manufacturer'=>'MIKOYAN','model'=>'MiG-27','icao_type_designator'=>'MG23','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-E'],
            ['manufacturer'=>'MIKOYAN','model'=>'MiG-25','icao_type_designator'=>'MG25','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-E'],
            ['manufacturer'=>'MIKOYAN','model'=>'MiG-33','icao_type_designator'=>'MG29','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-E'],
            ['manufacturer'=>'MIKOYAN','model'=>'MiG-31','icao_type_designator'=>'MG31','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-E'],
            ['manufacturer'=>'MIKOYAN','model'=>'MiG 1-44','icao_type_designator'=>'MG44','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-E'],
            ['manufacturer'=>'DASSAULT','model'=>'Vajra','icao_type_designator'=>'MIR2','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-E'],
            ['manufacturer'=>'DASSAULT','model'=>'Mirage F1','icao_type_designator'=>'MRF1','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-E'],
            ['manufacturer'=>'MITSUBISHI','model'=>'MRJ-70','icao_type_designator'=>'MRJ7','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-E'],
            ['manufacturer'=>'MITSUBISHI','model'=>'MRJ-90','icao_type_designator'=>'MRJ9','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-E'],
            ['manufacturer'=>'MYASISHCHEV','model'=>'3M','icao_type_designator'=>'MYA4','icao_legacy_wtc'=>'H','recat_eu_wtc'=>'CAT-C'],
            ['manufacturer'=>'NUSANTARA','model'=>'N-250','icao_type_designator'=>'N250','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-E'],
            ['manufacturer'=>'NORTHROP GRUMMAN','model'=>'E-2 Hawkeye','icao_type_designator'=>'E2','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-E'],
            ['manufacturer'=>'BOEING','model'=>'Mercury','icao_type_designator'=>'E6','icao_legacy_wtc'=>'H','recat_eu_wtc'=>'CAT-C'],
            ['manufacturer'=>'IRKUT','model'=>'MC-21-300','icao_type_designator'=>'MC23','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-D'],
            ['manufacturer'=>'DASSAULT','model'=>'Rafale','icao_type_designator'=>'RFAL','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-E'],
            ['manufacturer'=>'BRITISH AEROSPACE','model'=>'RJ-100','icao_type_designator'=>'RJ1H','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-E'],
            ['manufacturer'=>'BRITISH AEROSPACE','model'=>'RJ-70','icao_type_designator'=>'RJ70','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-E'],
            ['manufacturer'=>'BRITISH AEROSPACE','model'=>'RJ-85','icao_type_designator'=>'RJ85','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-E'],
            ['manufacturer'=>'BOEING','model'=>'TC-135','icao_type_designator'=>'R135','icao_legacy_wtc'=>'H','recat_eu_wtc'=>'CAT-C'],
            ['manufacturer'=>'SAAB','model'=>'2000','icao_type_designator'=>'SB20','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-E'],
            ['manufacturer'=>'VALMET','model'=>'Draken','icao_type_designator'=>'SB35','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-E'],
            ['manufacturer'=>'SAAB','model'=>'AJS37 Viggen','icao_type_designator'=>'SB37','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-E'],
            ['manufacturer'=>'LOCKHEED','model'=>'L-394 Viking','icao_type_designator'=>'S3','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-E'],
            ['manufacturer'=>'SUKHOI','model'=>'S-37 Berkut','icao_type_designator'=>'S37','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-E'],
            ['manufacturer'=>'SUKHOI','model'=>'Su-22','icao_type_designator'=>'SU17','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-E'],
            ['manufacturer'=>'SUKHOI','model'=>'Su-24','icao_type_designator'=>'SU24','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-E'],
            ['manufacturer'=>'SUKHOI','model'=>'Su-25 Scorpion','icao_type_designator'=>'SU25','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-E'],
            ['manufacturer'=>'SUKHOI','model'=>'JJ-11','icao_type_designator'=>'SU27','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-E'],
            ['manufacturer'=>'SUKHOI','model'=>'Su57','icao_type_designator'=>'SU57','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-E'],
            ['manufacturer'=>'SUKHOI','model'=>'Superjet 100-95','icao_type_designator'=>'SU95','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-E'],
            ['manufacturer'=>'PANAVIA','model'=>'Tornado','icao_type_designator'=>'TOR','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-E'],
            ['manufacturer'=>'TUPOLEV','model'=>'Tu-134','icao_type_designator'=>'T134','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-E'],
            ['manufacturer'=>'TUPOLEV','model'=>'Tu-214','icao_type_designator'=>'T204','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-C'],
            ['manufacturer'=>'TUPOLEV','model'=>'Tu-22M','icao_type_designator'=>'T22M','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-C'],
            ['manufacturer'=>'TUPOLEV','model'=>'Tu-160','icao_type_designator'=>'T160','icao_legacy_wtc'=>'H','recat_eu_wtc'=>'Special'],
            ['manufacturer'=>'TUPOLEV','model'=>'Tu-142','icao_type_designator'=>'TU95','icao_legacy_wtc'=>'H','recat_eu_wtc'=>'CAT-C'],
            ['manufacturer'=>'TUPOLEV','model'=>'Tu-22','icao_type_designator'=>'TU22','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-C'],
            ['manufacturer'=>'TUPOLEV','model'=>'Tu-334','icao_type_designator'=>'T334','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-E'],
            ['manufacturer'=>'LOCKHEED MARTIN','model'=>'Lightning II (F-35B)','icao_type_designator'=>'VF35','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-E'],
            ['manufacturer'=>'SUD','model'=>'SO-4050 Vautour','icao_type_designator'=>'VAUT','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-E'],
            ['manufacturer'=>'MARTIN','model'=>'272','icao_type_designator'=>'WB57','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-E'],
            ['manufacturer'=>'YAKOVLEV','model'=>'Yak-28','icao_type_designator'=>'YK28','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-E'],
            ['manufacturer'=>'YAKOVLEV','model'=>'Yak-40','icao_type_designator'=>'YK40','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-E'],
            ['manufacturer'=>'YAKOVLEV','model'=>'Yak-42','icao_type_designator'=>'YK42','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-D'],
            ['manufacturer'=>'NAMC','model'=>'YS-11','icao_type_designator'=>'YS11','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-E'],
            ['manufacturer'=>'NORTHROP GRUMMAN','model'=>'Spirit','icao_type_designator'=>'B2','icao_legacy_wtc'=>'H','recat_eu_wtc'=>'Special'],
            ['manufacturer'=>'BOEING','model'=>'B-52 Stratofortress','icao_type_designator'=>'B52','icao_legacy_wtc'=>'H','recat_eu_wtc'=>'Special'],
            ['manufacturer'=>'SCALED','model'=>'351 Stratolaunch','icao_type_designator'=>'SLCH','icao_legacy_wtc'=>'H','recat_eu_wtc'=>'Special'],
            ['manufacturer'=>'TUPOLEV','model'=>'Tu-154','icao_type_designator'=>'T154','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-D'],
            ['manufacturer'=>'ILYUSHIN','model'=>'Il-20','icao_type_designator'=>'IL18','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-D'],
            ['manufacturer'=>'ILYUSHIN','model'=>'Il-38','icao_type_designator'=>'IL38','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-D'],
            ['manufacturer'=>'DOUGLAS','model'=>'DC-4','icao_type_designator'=>'DC4','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-D'],
            ['manufacturer'=>'DOUGLAS','model'=>'DC-6','icao_type_designator'=>'DC6','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-D'],
            ['manufacturer'=>'DOUGLAS','model'=>'DC-7','icao_type_designator'=>'DC7','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-D'],
            ['manufacturer'=>'FAIRCHILD','model'=>'C-119 Flying Boxcar','icao_type_designator'=>'C119','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-D'],
            ['manufacturer'=>'FAIRCHILD','model'=>'C-123 Provider','icao_type_designator'=>'C123','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-D'],
            ['manufacturer'=>'BOEING','model'=>'B-29 Superfortress','icao_type_designator'=>'B29','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-D'],
            ['manufacturer'=>'CONVAIR','model'=>'Liberator','icao_type_designator'=>'B24','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-D'],
            ['manufacturer'=>'MCDONNELL DOUGLAS','model'=>'Globemaster 3','icao_type_designator'=>'C17','icao_legacy_wtc'=>'H','recat_eu_wtc'=>'CAT-C'],
            ['manufacturer'=>'LOCKHEED','model'=>'C-121 Constellation','icao_type_designator'=>'CONI','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-D'],
            ['manufacturer'=>'TRANSALL','model'=>'C-160','icao_type_designator'=>'C160','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-D'],
            ['manufacturer'=>'CURTISS','model'=>'C-46 Commando','icao_type_designator'=>'C46','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-D'],
            ['manufacturer'=>'BOEING','model'=>'727-100RE Super 27','icao_type_designator'=>'R721','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-D'],
            ['manufacturer'=>'BOEING','model'=>'727-200RE Super 27','icao_type_designator'=>'R722','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-D'],
            ['manufacturer'=>'LOCKHEED MARTIN','model'=>'P-3 Orion','icao_type_designator'=>'P3','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-E'],
            ['manufacturer'=>'BOEING','model'=>'P-8 Poseidon','icao_type_designator'=>'P8','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-D'],
            ['manufacturer'=>'KAWASAKI','model'=>'XP-1','icao_type_designator'=>'P1','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-D'],
            ['manufacturer'=>'NORTHROP','model'=>'Black Widow','icao_type_designator'=>'P61','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-E'],
            ['manufacturer'=>'MCDONNELL DOUGLAS','model'=>'YC-15','icao_type_designator'=>'C15','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-D'],
            ['manufacturer'=>'DASSAULT','model'=>'1150 Atlantic','icao_type_designator'=>'ATLA','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-D'],
            ['manufacturer'=>'CANADAIR','model'=>'CL-44-0 Guppy','icao_type_designator'=>'CL4G','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-D'],
            ['manufacturer'=>'AVIATION TRADERS','model'=>'ATL-98 Carvair','icao_type_designator'=>'CARV','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-D'],
            ['manufacturer'=>'BOEING','model'=>'C-97 Stratofreighter','icao_type_designator'=>'C97','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-D'],
            ['manufacturer'=>'MYASISHCHEV','model'=>'M-17 Stratosfera','icao_type_designator'=>'M17','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-D'],
            ['manufacturer'=>'MYASISHCHEV','model'=>'Geophysica','icao_type_designator'=>'M55','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-D'],
            ['manufacturer'=>'XIAN','model'=>'H-6','icao_type_designator'=>'TU16','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-D'],
            ['manufacturer'=>'FAIRCHILD','model'=>'C-82 Packet','icao_type_designator'=>'C82','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-F'],
            ['manufacturer'=>'NORTHROP','model'=>'C-125 Raider','icao_type_designator'=>'C125','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-E'],
            ['manufacturer'=>'ANTONOV','model'=>'An-70','icao_type_designator'=>'AN70','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-C'],
            ['manufacturer'=>'ROCKWELL','model'=>'Lancer','icao_type_designator'=>'B1','icao_legacy_wtc'=>'H','recat_eu_wtc'=>'CAT-C'],
            ['manufacturer'=>'BOEING','model'=>'C-135 Stratolifter','icao_type_designator'=>'C135','icao_legacy_wtc'=>'H','recat_eu_wtc'=>'CAT-C'],
            ['manufacturer'=>'HAWKER BEECHCRAFT','model'=>'4000 Hawker Horizon','icao_type_designator'=>'HA4T','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-E'],
            ['manufacturer'=>'NORTHROP GRUMMAN','model'=>'RQ-4 Global Hawk','icao_type_designator'=>'Q4','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'None'],
            ['manufacturer'=>'NANCHANG','model'=>'A-5','icao_type_designator'=>'Q5','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-E'],
            ['manufacturer'=>'BOEING','model'=>'Stingray','icao_type_designator'=>'Q25','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'None'],
            ['manufacturer'=>'BOEING','model'=>'BTX-1','icao_type_designator'=>'BT7','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'None'],
            ['manufacturer'=>'NORTHROP GRUMMAN','model'=>'X-47B','icao_type_designator'=>'X47B','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'None'],
            ['manufacturer'=>'LOCKHEED','model'=>'F-117 Nighthawk','icao_type_designator'=>'F117','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-E'],
            ['manufacturer'=>'LOCKHEED','model'=>'F-104 Starfighter','icao_type_designator'=>'F104','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-F'],
            ['manufacturer'=>'NORTH AMERICAN','model'=>'F-86 Sabre','icao_type_designator'=>'F86','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-F'],
            ['manufacturer'=>'NORTHROP','model'=>'F-5 Tiger 2','icao_type_designator'=>'F5','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-F'],
            ['manufacturer'=>'MITSUBISHI','model'=>'F-1','icao_type_designator'=>'F1','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-F'],
            ['manufacturer'=>'DASSAULT','model'=>'Falcon 10','icao_type_designator'=>'FA10','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-F'],
            ['manufacturer'=>'DASSAULT','model'=>'Falcon 20','icao_type_designator'=>'FA20','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-F'],
            ['manufacturer'=>'CESSNA','model'=>'E530 Scorpion','icao_type_designator'=>'E530','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-F'],
            ['manufacturer'=>'EMBRAER','model'=>'EMB-505 Phenom 300','icao_type_designator'=>'E55P','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-F'],
            ['manufacturer'=>'LEARJET','model'=>'31','icao_type_designator'=>'LJ31','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-F'],
            ['manufacturer'=>'LEARJET','model'=>'35','icao_type_designator'=>'LJ35','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-F'],
            ['manufacturer'=>'LEARJET','model'=>'40','icao_type_designator'=>'LJ40','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-F'],
            ['manufacturer'=>'LEARJET','model'=>'45','icao_type_designator'=>'LJ45','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-F'],
            ['manufacturer'=>'LEARJET','model'=>'55','icao_type_designator'=>'LJ55','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-F'],
            ['manufacturer'=>'LEARJET','model'=>'60','icao_type_designator'=>'LJ60','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-F'],
            ['manufacturer'=>'LEARJET','model'=>'70','icao_type_designator'=>'LJ70','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-F'],
            ['manufacturer'=>'LEARJET','model'=>'75','icao_type_designator'=>'LJ75','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-F'],
            ['manufacturer'=>'LEARJET','model'=>'85','icao_type_designator'=>'LJ85','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-E'],
            ['manufacturer'=>'CESSNA','model'=>'680 Citation Sovereign','icao_type_designator'=>'C680','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-F'],
            ['manufacturer'=>'CESSNA','model'=>'680A Citation Latitude','icao_type_designator'=>'C68A','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-F'],
            ['manufacturer'=>'CESSNA','model'=>'650 Citation 6','icao_type_designator'=>'C650','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-F'],
            ['manufacturer'=>'CESSNA','model'=>'560 Citation 5','icao_type_designator'=>'C560','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-F'],
            ['manufacturer'=>'CESSNA','model'=>'560XL Citation Excel','icao_type_designator'=>'C56X','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-F'],
            ['manufacturer'=>'PILATUS','model'=>'PC-24','icao_type_designator'=>'PC24','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-F'],
            ['manufacturer'=>'IAI','model'=>'Gulfstream G100','icao_type_designator'=>'ASTR','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-F'],
            ['manufacturer'=>'IAI','model'=>'Gulfstream G150','icao_type_designator'=>'G150','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-F'],
            ['manufacturer'=>'RAYTHEON','model'=>'Hawker 800','icao_type_designator'=>'H25B','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-F'],
            ['manufacturer'=>'RAYTHEON','model'=>'Hawker 1000','icao_type_designator'=>'H25C','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-F'],
            ['manufacturer'=>'HAWKER SIDDELEY','model'=>'HS-125-1','icao_type_designator'=>'H25A','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-F'],
            ['manufacturer'=>'BERIEV','model'=>'Be-200 Altair','icao_type_designator'=>'BER2','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-D'],
            ['manufacturer'=>'BERIEV','model'=>'Albatross','icao_type_designator'=>'BER4','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-D'],
            ['manufacturer'=>'CANADAIR','model'=>'A-10 Catalina','icao_type_designator'=>'CAT','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-E'],
            ['manufacturer'=>'CANADAIR','model'=>'CL-215','icao_type_designator'=>'CL2P','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-E'],
            ['manufacturer'=>'CANADAIR','model'=>'CL-215T','icao_type_designator'=>'CL2T','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-E'],
            ['manufacturer'=>'MARTIN','model'=>'170 Mars','icao_type_designator'=>'MARS','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-D'],
            ['manufacturer'=>'SHORT','model'=>'S-25 Sandringham','icao_type_designator'=>'SAND','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-D'],
            ['manufacturer'=>'HARBIN','model'=>'PS-5','icao_type_designator'=>'SH5','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-D'],
            ['manufacturer'=>'SHIN MEIWA','model'=>'US-1','icao_type_designator'=>'US1','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-D'],
            ['manufacturer'=>'SHINMAYWA','model'=>'US-2','icao_type_designator'=>'US2','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-D'],
            ['manufacturer'=>'BELL-BOEING','model'=>'MV-22 Osprey','icao_type_designator'=>'V22','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-E'],
            ['manufacturer'=>'AGUSTAWESTLAND','model'=>'AW-609','icao_type_designator'=>'B609','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'TBC'],
            ['manufacturer'=>'BELL','model'=>'Valor','icao_type_designator'=>'V280','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'TBC'],
            ['manufacturer'=>'HARBIN','model'=>'Aircar','icao_type_designator'=>'Y12F','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'TBC'],
            ['manufacturer'=>'XIAN','model'=>'Y-20 Kunpeng','icao_type_designator'=>'Y20','icao_legacy_wtc'=>'H','recat_eu_wtc'=>'TBC'],
            ['manufacturer'=>'SCALED','model'=>'White Knight Two','icao_type_designator'=>'WHK2','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'TBC'],
            ['manufacturer'=>'BERIEV','model'=>'Be-12 Tchaika','icao_type_designator'=>'BE12','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-E'],
            ['manufacturer'=>'GRUMMAN','model'=>'SA-16 Albatross','icao_type_designator'=>'U16','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-F'],
            ['manufacturer'=>'CESSNA','model'=>'172','icao_type_designator'=>'C172','icao_legacy_wtc'=>'L','recat_eu_wtc'=>'CAT-F'],
            ['manufacturer'=>'CESSNA','model'=>'182','icao_type_designator'=>'C182','icao_legacy_wtc'=>'L','recat_eu_wtc'=>'CAT-F'],
            ['manufacturer'=>'CESSNA','model'=>'150','icao_type_designator'=>'C150','icao_legacy_wtc'=>'L','recat_eu_wtc'=>'CAT-F'],
            ['manufacturer'=>'CESSNA','model'=>'152','icao_type_designator'=>'C152','icao_legacy_wtc'=>'L','recat_eu_wtc'=>'CAT-F'],
            ['manufacturer'=>'CESSNA','model'=>'206 Super Skywagon','icao_type_designator'=>'C206','icao_legacy_wtc'=>'L','recat_eu_wtc'=>'CAT-F'],
            ['manufacturer'=>'CESSNA','model'=>'210 Centurion','icao_type_designator'=>'C210','icao_legacy_wtc'=>'L','recat_eu_wtc'=>'CAT-F'],
            ['manufacturer'=>'CESSNA','model'=>'Citation','icao_type_designator'=>'C500','icao_legacy_wtc'=>'L','recat_eu_wtc'=>'CAT-F'],
            ['manufacturer'=>'CESSNA','model'=>'525 CitationJet','icao_type_designator'=>'C525','icao_legacy_wtc'=>'L','recat_eu_wtc'=>'CAT-F'],
            ['manufacturer'=>'CESSNA','model'=>'Citation 2','icao_type_designator'=>'C550','icao_legacy_wtc'=>'L','recat_eu_wtc'=>'CAT-F'],
            ['manufacturer'=>'PIPER','model'=>'PA-28-181 Cherokee Archer 2','icao_type_designator'=>'P28A','icao_legacy_wtc'=>'L','recat_eu_wtc'=>'CAT-F'],
            ['manufacturer'=>'PIPER','model'=>'PA-34 Seneca','icao_type_designator'=>'PA34','icao_legacy_wtc'=>'L','recat_eu_wtc'=>'CAT-F'],
            ['manufacturer'=>'PIPER','model'=>'PA-31-350 Navajo Chieftain','icao_type_designator'=>'PA31','icao_legacy_wtc'=>'L','recat_eu_wtc'=>'CAT-F'],
            ['manufacturer'=>'PIPER','model'=>'PA-46-310P Malibu','icao_type_designator'=>'PA46','icao_legacy_wtc'=>'L','recat_eu_wtc'=>'CAT-F'],
            ['manufacturer'=>'PIPER','model'=>'PA-46-500TP Malibu Meridian','icao_type_designator'=>'P46T','icao_legacy_wtc'=>'L','recat_eu_wtc'=>'CAT-F'],
            ['manufacturer'=>'BEECH','model'=>'55 Baron','icao_type_designator'=>'BE55','icao_legacy_wtc'=>'L','recat_eu_wtc'=>'CAT-F'],
            ['manufacturer'=>'BEECH','model'=>'58 Baron','icao_type_designator'=>'BE58','icao_legacy_wtc'=>'L','recat_eu_wtc'=>'CAT-F'],
            ['manufacturer'=>'BEECH','model'=>'Bonanza 36','icao_type_designator'=>'BE36','icao_legacy_wtc'=>'L','recat_eu_wtc'=>'CAT-F'],
            ['manufacturer'=>'BEECH','model'=>'90 King Air','icao_type_designator'=>'BE9L','icao_legacy_wtc'=>'L','recat_eu_wtc'=>'CAT-F'],
            ['manufacturer'=>'BEECH','model'=>'300 Super King Air','icao_type_designator'=>'BE30','icao_legacy_wtc'=>'L','recat_eu_wtc'=>'CAT-F'],
            ['manufacturer'=>'DE HAVILLAND CANADA','model'=>'DHC-2 Beaver','icao_type_designator'=>'DHC2','icao_legacy_wtc'=>'L','recat_eu_wtc'=>'CAT-F'],
            ['manufacturer'=>'DE HAVILLAND CANADA','model'=>'DHC-3 Otter','icao_type_designator'=>'DHC3','icao_legacy_wtc'=>'L','recat_eu_wtc'=>'CAT-F'],
            ['manufacturer'=>'VIKING','model'=>'DHC-6 Twin Otter','icao_type_designator'=>'DHC6','icao_legacy_wtc'=>'L','recat_eu_wtc'=>'CAT-F'],
            ['manufacturer'=>'DIAMOND','model'=>'Katana (DA-40)','icao_type_designator'=>'DA40','icao_legacy_wtc'=>'L','recat_eu_wtc'=>'CAT-F'],
            ['manufacturer'=>'DIAMOND','model'=>'Twin Star','icao_type_designator'=>'DA42','icao_legacy_wtc'=>'L','recat_eu_wtc'=>'CAT-F'],
            ['manufacturer'=>'DIAMOND','model'=>'DA-62','icao_type_designator'=>'DA62','icao_legacy_wtc'=>'L','recat_eu_wtc'=>'CAT-F'],
            ['manufacturer'=>'CIRRUS','model'=>'SR-22','icao_type_designator'=>'SR22','icao_legacy_wtc'=>'L','recat_eu_wtc'=>'CAT-F'],
            ['manufacturer'=>'CIRRUS','model'=>'SR-20 SRV','icao_type_designator'=>'SR20','icao_legacy_wtc'=>'L','recat_eu_wtc'=>'CAT-F'],
            ['manufacturer'=>'PILATUS','model'=>'Eagle PC12','icao_type_designator'=>'PC12','icao_legacy_wtc'=>'L','recat_eu_wtc'=>'CAT-F'],
            ['manufacturer'=>'PILATUS','model'=>'PC-7 Turbo Trainer','icao_type_designator'=>'PC7','icao_legacy_wtc'=>'L','recat_eu_wtc'=>'CAT-F'],
            ['manufacturer'=>'PILATUS','model'=>'PC-9','icao_type_designator'=>'PC9','icao_legacy_wtc'=>'L','recat_eu_wtc'=>'CAT-F'],
            ['manufacturer'=>'PILATUS','model'=>'PC-21','icao_type_designator'=>'PC21','icao_legacy_wtc'=>'L','recat_eu_wtc'=>'CAT-F'],
            ['manufacturer'=>'TECNAM','model'=>'P-2002 Sierra','icao_type_designator'=>'SIRA','icao_legacy_wtc'=>'L','recat_eu_wtc'=>'CAT-F'],
            ['manufacturer'=>'SOCATA','model'=>'TBM-700','icao_type_designator'=>'TBM7','icao_legacy_wtc'=>'L','recat_eu_wtc'=>'CAT-F'],
            ['manufacturer'=>'SOCATA','model'=>'TBM-850','icao_type_designator'=>'TBM8','icao_legacy_wtc'=>'L','recat_eu_wtc'=>'CAT-F'],
            ['manufacturer'=>'SOCATA','model'=>'TBM-900','icao_type_designator'=>'TBM9','icao_legacy_wtc'=>'L','recat_eu_wtc'=>'CAT-F'],
            ['manufacturer'=>'TBM','model'=>'TBM-700','icao_type_designator'=>'TBM7','icao_legacy_wtc'=>'L','recat_eu_wtc'=>'CAT-F'],
            ['manufacturer'=>'EMBRAER','model'=>'EMB 500 Phenom 100','icao_type_designator'=>'E50P','icao_legacy_wtc'=>'L','recat_eu_wtc'=>'CAT-F'],
            ['manufacturer'=>'NORTH AMERICAN','model'=>'Harvard','icao_type_designator'=>'T6','icao_legacy_wtc'=>'L','recat_eu_wtc'=>'CAT-F'],
            ['manufacturer'=>'BRITISH AEROSPACE','model'=>'Jetstream 41','icao_type_designator'=>'JS41','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-F'],
            ['manufacturer'=>'BRITISH AEROSPACE','model'=>'BAe-3100 Jetstream 31','icao_type_designator'=>'JS31','icao_legacy_wtc'=>'L','recat_eu_wtc'=>'CAT-F'],
            ['manufacturer'=>'SHORT','model'=>'SD3-60','icao_type_designator'=>'SH36','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-F'],
            ['manufacturer'=>'EMBRAER','model'=>'EMB-120 Brasilia','icao_type_designator'=>'E120','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-F'],
            ['manufacturer'=>'DOUGLAS','model'=>'DC-3','icao_type_designator'=>'DC3','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-F'],
            ['manufacturer'=>'DOUGLAS','model'=>'DC-2','icao_type_designator'=>'DC2','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-F'],
            ['manufacturer'=>'SAAB-FAIRCHILD','model'=>'SF-340','icao_type_designator'=>'SF34','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-F'],
            ['manufacturer'=>'CESSNA','model'=>'402','icao_type_designator'=>'C402','icao_legacy_wtc'=>'L','recat_eu_wtc'=>'CAT-F'],
            ['manufacturer'=>'CESSNA','model'=>'404 Titan','icao_type_designator'=>'C404','icao_legacy_wtc'=>'L','recat_eu_wtc'=>'CAT-F'],
            ['manufacturer'=>'CESSNA','model'=>'421 Golden Eagle','icao_type_designator'=>'C421','icao_legacy_wtc'=>'L','recat_eu_wtc'=>'CAT-F'],
            ['manufacturer'=>'CESSNA','model'=>'408 SkyCourier','icao_type_designator'=>'C408','icao_legacy_wtc'=>'L','recat_eu_wtc'=>'CAT-F'],
        ];
    }

    private function helicopters(): array
    {
        return [
            ['manufacturer'=>'AGUSTA','model'=>'A-109','icao_type_designator'=>'A109','icao_legacy_wtc'=>'L','recat_eu_wtc'=>'CAT-F'],
            ['manufacturer'=>'AGUSTA','model'=>'AW-139','icao_type_designator'=>'A139','icao_legacy_wtc'=>'L','recat_eu_wtc'=>'CAT-F'],
            ['manufacturer'=>'AGUSTAWESTLAND','model'=>'AW-169','icao_type_designator'=>'A169','icao_legacy_wtc'=>'L','recat_eu_wtc'=>'CAT-F'],
            ['manufacturer'=>'AGUSTAWESTLAND','model'=>'AW-189','icao_type_designator'=>'A189','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-F'],
            ['manufacturer'=>'AGUSTA','model'=>'AW-149','icao_type_designator'=>'A149','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-F'],
            ['manufacturer'=>'AGUSTA','model'=>'A-129 Mangusta','icao_type_designator'=>'A129','icao_legacy_wtc'=>'L','recat_eu_wtc'=>'CAT-F'],
            ['manufacturer'=>'AGUSTA','model'=>'A-119 Koala','icao_type_designator'=>'A119','icao_legacy_wtc'=>'L','recat_eu_wtc'=>'CAT-F'],
            ['manufacturer'=>'AEROSPATIALE','model'=>'Alouette 2','icao_type_designator'=>'ALO2','icao_legacy_wtc'=>'L','recat_eu_wtc'=>'CAT-F'],
            ['manufacturer'=>'AEROSPATIALE','model'=>'Alouette 3','icao_type_designator'=>'ALO3','icao_legacy_wtc'=>'L','recat_eu_wtc'=>'CAT-F'],
            ['manufacturer'=>'AEROSPATIALE','model'=>'AS-332B Super Puma','icao_type_designator'=>'AS32','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-F'],
            ['manufacturer'=>'AEROSPATIALE','model'=>'AS-332L2 Super Puma Mk2','icao_type_designator'=>'AS3B','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-F'],
            ['manufacturer'=>'AEROSPATIALE','model'=>'AS-350 Ecureuil','icao_type_designator'=>'AS50','icao_legacy_wtc'=>'L','recat_eu_wtc'=>'CAT-F'],
            ['manufacturer'=>'AEROSPATIALE','model'=>'AS-355 Ecureuil 2','icao_type_designator'=>'AS55','icao_legacy_wtc'=>'L','recat_eu_wtc'=>'CAT-F'],
            ['manufacturer'=>'AEROSPATIALE','model'=>'AS-365 Dauphin 2','icao_type_designator'=>'AS65','icao_legacy_wtc'=>'L','recat_eu_wtc'=>'CAT-F'],
            ['manufacturer'=>'AEROSPATIALE','model'=>'SA-321 Super Frelon','icao_type_designator'=>'FREL','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-F'],
            ['manufacturer'=>'AEROSPATIALE','model'=>'SA-330 Puma','icao_type_designator'=>'PUMA','icao_legacy_wtc'=>'L','recat_eu_wtc'=>'CAT-F'],
            ['manufacturer'=>'AEROSPATIALE','model'=>'Lama','icao_type_designator'=>'LAMA','icao_legacy_wtc'=>'L','recat_eu_wtc'=>'CAT-F'],
            ['manufacturer'=>'AEROSPATIALE','model'=>'SA-360 Dauphin','icao_type_designator'=>'S360','icao_legacy_wtc'=>'L','recat_eu_wtc'=>'CAT-F'],
            ['manufacturer'=>'AGUSTAWESTLAND','model'=>'EH-101 Merlin','icao_type_designator'=>'EH10','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-F'],
            ['manufacturer'=>'AIRBUS HELICOPTERS','model'=>'H-120 Colibri','icao_type_designator'=>'EC20','icao_legacy_wtc'=>'L','recat_eu_wtc'=>'CAT-F'],
            ['manufacturer'=>'AIRBUS HELICOPTERS','model'=>'H-225 Super Puma Mk2+','icao_type_designator'=>'EC25','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-F'],
            ['manufacturer'=>'AIRBUS HELICOPTERS','model'=>'H-130','icao_type_designator'=>'EC30','icao_legacy_wtc'=>'L','recat_eu_wtc'=>'CAT-F'],
            ['manufacturer'=>'AIRBUS HELICOPTERS','model'=>'EC-135','icao_type_designator'=>'EC35','icao_legacy_wtc'=>'L','recat_eu_wtc'=>'CAT-F'],
            ['manufacturer'=>'AIRBUS HELICOPTERS','model'=>'H-145','icao_type_designator'=>'EC45','icao_legacy_wtc'=>'L','recat_eu_wtc'=>'CAT-F'],
            ['manufacturer'=>'AIRBUS HELICOPTERS','model'=>'H-155','icao_type_designator'=>'EC55','icao_legacy_wtc'=>'L','recat_eu_wtc'=>'CAT-F'],
            ['manufacturer'=>'AIRBUS HELICOPTERS','model'=>'EC-175','icao_type_designator'=>'EC75','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-F'],
            ['manufacturer'=>'AIRBUS HELICOPTERS','model'=>'H-160','icao_type_designator'=>'H160','icao_legacy_wtc'=>'L','recat_eu_wtc'=>'CAT-F'],
            ['manufacturer'=>'BELL','model'=>'206B JetRanger','icao_type_designator'=>'B06','icao_legacy_wtc'=>'L','recat_eu_wtc'=>'CAT-F'],
            ['manufacturer'=>'BELL','model'=>'206LT TwinRanger','icao_type_designator'=>'B06T','icao_legacy_wtc'=>'L','recat_eu_wtc'=>'CAT-F'],
            ['manufacturer'=>'BELL','model'=>'212','icao_type_designator'=>'B212','icao_legacy_wtc'=>'L','recat_eu_wtc'=>'CAT-F'],
            ['manufacturer'=>'BELL','model'=>'214A Isfahan','icao_type_designator'=>'B214','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-F'],
            ['manufacturer'=>'BELL','model'=>'222','icao_type_designator'=>'B222','icao_legacy_wtc'=>'L','recat_eu_wtc'=>'CAT-F'],
            ['manufacturer'=>'BELL','model'=>'230','icao_type_designator'=>'B230','icao_legacy_wtc'=>'L','recat_eu_wtc'=>'CAT-F'],
            ['manufacturer'=>'BELL','model'=>'407','icao_type_designator'=>'B407','icao_legacy_wtc'=>'L','recat_eu_wtc'=>'CAT-F'],
            ['manufacturer'=>'BELL','model'=>'412','icao_type_designator'=>'B412','icao_legacy_wtc'=>'L','recat_eu_wtc'=>'CAT-F'],
            ['manufacturer'=>'BELL','model'=>'427','icao_type_designator'=>'B427','icao_legacy_wtc'=>'L','recat_eu_wtc'=>'CAT-F'],
            ['manufacturer'=>'BELL','model'=>'429 GlobalRanger','icao_type_designator'=>'B429','icao_legacy_wtc'=>'L','recat_eu_wtc'=>'CAT-F'],
            ['manufacturer'=>'BELL','model'=>'430','icao_type_designator'=>'B430','icao_legacy_wtc'=>'L','recat_eu_wtc'=>'CAT-F'],
            ['manufacturer'=>'BELL','model'=>'47G','icao_type_designator'=>'B47G','icao_legacy_wtc'=>'L','recat_eu_wtc'=>'CAT-F'],
            ['manufacturer'=>'BELL','model'=>'47J Ranger','icao_type_designator'=>'B47J','icao_legacy_wtc'=>'L','recat_eu_wtc'=>'CAT-F'],
            ['manufacturer'=>'BELL','model'=>'505 Jet Ranger X','icao_type_designator'=>'B505','icao_legacy_wtc'=>'L','recat_eu_wtc'=>'CAT-F'],
            ['manufacturer'=>'BELL','model'=>'525 Relentless','icao_type_designator'=>'B525','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-F'],
            ['manufacturer'=>'BELL','model'=>'209 HueyCobra','icao_type_designator'=>'HUCO','icao_legacy_wtc'=>'L','recat_eu_wtc'=>'CAT-F'],
            ['manufacturer'=>'BELL','model'=>'209 SuperCobra','icao_type_designator'=>'SUCO','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-F'],
            ['manufacturer'=>'BELL','model'=>'214ST SuperTransport','icao_type_designator'=>'BSTP','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-F'],
            ['manufacturer'=>'BELL','model'=>'UH-1Y','icao_type_designator'=>'UH1Y','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-F'],
            ['manufacturer'=>'BELL','model'=>'UH-1H Iroquois','icao_type_designator'=>'UH1','icao_legacy_wtc'=>'L','recat_eu_wtc'=>'CAT-F'],
            ['manufacturer'=>'BOLKOW','model'=>'BO-105','icao_type_designator'=>'B105','icao_legacy_wtc'=>'L','recat_eu_wtc'=>'CAT-F'],
            ['manufacturer'=>'BOEING VERTOL','model'=>'107','icao_type_designator'=>'H46','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-F'],
            ['manufacturer'=>'BOEING','model'=>'CH-47 Chinook','icao_type_designator'=>'H47','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-E'],
            ['manufacturer'=>'BOEING','model'=>'AH-64 Apache','icao_type_designator'=>'H64','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-F'],
            ['manufacturer'=>'BRANTLY','model'=>'305','icao_type_designator'=>'B305','icao_legacy_wtc'=>'L','recat_eu_wtc'=>'CAT-F'],
            ['manufacturer'=>'BRANTLY','model'=>'B-2','icao_type_designator'=>'BRB2','icao_legacy_wtc'=>'L','recat_eu_wtc'=>'CAT-F'],
            ['manufacturer'=>'ENSTROM','model'=>'F-28','icao_type_designator'=>'EN28','icao_legacy_wtc'=>'L','recat_eu_wtc'=>'CAT-F'],
            ['manufacturer'=>'ENSTROM','model'=>'480','icao_type_designator'=>'EN48','icao_legacy_wtc'=>'L','recat_eu_wtc'=>'CAT-F'],
            ['manufacturer'=>'GUIMBAL','model'=>'G-2 Cabri','icao_type_designator'=>'G2CA','icao_legacy_wtc'=>'L','recat_eu_wtc'=>'CAT-F'],
            ['manufacturer'=>'HILLER','model'=>'UH-12E','icao_type_designator'=>'UH12','icao_legacy_wtc'=>'L','recat_eu_wtc'=>'CAT-F'],
            ['manufacturer'=>'HINDUSTAN','model'=>'ALH Dhruv','icao_type_designator'=>'ALH','icao_legacy_wtc'=>'L','recat_eu_wtc'=>'CAT-F'],
            ['manufacturer'=>'HINDUSTAN','model'=>'LCH','icao_type_designator'=>'LCH','icao_legacy_wtc'=>'L','recat_eu_wtc'=>'CAT-F'],
            ['manufacturer'=>'HUGHES','model'=>'269','icao_type_designator'=>'H269','icao_legacy_wtc'=>'L','recat_eu_wtc'=>'CAT-F'],
            ['manufacturer'=>'HUGHES','model'=>'500 Defender','icao_type_designator'=>'H500','icao_legacy_wtc'=>'L','recat_eu_wtc'=>'CAT-F'],
            ['manufacturer'=>'KAMAN','model'=>'SH-2 Seasprite','icao_type_designator'=>'H2','icao_legacy_wtc'=>'L','recat_eu_wtc'=>'CAT-F'],
            ['manufacturer'=>'KAMAN','model'=>'HH-43B Huskie','icao_type_designator'=>'H43B','icao_legacy_wtc'=>'L','recat_eu_wtc'=>'CAT-F'],
            ['manufacturer'=>'KAMAN','model'=>'K-1200 K-Max','icao_type_designator'=>'KMAX','icao_legacy_wtc'=>'L','recat_eu_wtc'=>'CAT-F'],
            ['manufacturer'=>'KAMOV','model'=>'Ka-25','icao_type_designator'=>'KA25','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-F'],
            ['manufacturer'=>'KAMOV','model'=>'Ka-26','icao_type_designator'=>'KA26','icao_legacy_wtc'=>'L','recat_eu_wtc'=>'CAT-F'],
            ['manufacturer'=>'KAMOV','model'=>'Ka-27','icao_type_designator'=>'KA27','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-F'],
            ['manufacturer'=>'KAMOV','model'=>'Ka-50 Black Shark','icao_type_designator'=>'KA50','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-F'],
            ['manufacturer'=>'KAMOV','model'=>'Ka-52 Alligator','icao_type_designator'=>'KA52','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-F'],
            ['manufacturer'=>'KAMOV','model'=>'Ka-62','icao_type_designator'=>'KA62','icao_legacy_wtc'=>'L','recat_eu_wtc'=>'CAT-F'],
            ['manufacturer'=>'KAZAN','model'=>'Ansat','icao_type_designator'=>'ANST','icao_legacy_wtc'=>'L','recat_eu_wtc'=>'CAT-F'],
            ['manufacturer'=>'EUROCOPTER','model'=>'Tiger','icao_type_designator'=>'TIGR','icao_legacy_wtc'=>'L','recat_eu_wtc'=>'CAT-F'],
            ['manufacturer'=>'MBB-KAWASAKI','model'=>'BK-117','icao_type_designator'=>'BK17','icao_legacy_wtc'=>'L','recat_eu_wtc'=>'CAT-F'],
            ['manufacturer'=>'MIL','model'=>'Mi-2','icao_type_designator'=>'MI2','icao_legacy_wtc'=>'L','recat_eu_wtc'=>'CAT-F'],
            ['manufacturer'=>'MIL','model'=>'Mi-8','icao_type_designator'=>'MI8','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-F'],
            ['manufacturer'=>'MIL','model'=>'Mi-10','icao_type_designator'=>'MI10','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-D'],
            ['manufacturer'=>'MIL','model'=>'Mi-14','icao_type_designator'=>'MI14','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-F'],
            ['manufacturer'=>'MIL','model'=>'Mi-24','icao_type_designator'=>'MI24','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-F'],
            ['manufacturer'=>'MIL','model'=>'Mi-26','icao_type_designator'=>'MI26','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-D'],
            ['manufacturer'=>'MIL','model'=>'Mi-28','icao_type_designator'=>'MI28','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-F'],
            ['manufacturer'=>'MIL','model'=>'Mi-34','icao_type_designator'=>'MI34','icao_legacy_wtc'=>'L','recat_eu_wtc'=>'CAT-F'],
            ['manufacturer'=>'MIL','model'=>'Mi-38','icao_type_designator'=>'MI38','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-E'],
            ['manufacturer'=>'MIL','model'=>'Mi-4','icao_type_designator'=>'MI4','icao_legacy_wtc'=>'L','recat_eu_wtc'=>'CAT-F'],
            ['manufacturer'=>'MIL','model'=>'Mi-6','icao_type_designator'=>'MI6','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-D'],
            ['manufacturer'=>'NHI','model'=>'NH-90','icao_type_designator'=>'NH90','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-F'],
            ['manufacturer'=>'PZL-SWIDNIK','model'=>'SW-4 Maluch','icao_type_designator'=>'PSW4','icao_legacy_wtc'=>'L','recat_eu_wtc'=>'CAT-F'],
            ['manufacturer'=>'PZL-SWIDNIK','model'=>'W-3 Sokól','icao_type_designator'=>'W3','icao_legacy_wtc'=>'L','recat_eu_wtc'=>'CAT-F'],
            ['manufacturer'=>'ROBINSON','model'=>'R-22','icao_type_designator'=>'R22','icao_legacy_wtc'=>'L','recat_eu_wtc'=>'CAT-F'],
            ['manufacturer'=>'ROBINSON','model'=>'R-44 Raven','icao_type_designator'=>'R44','icao_legacy_wtc'=>'L','recat_eu_wtc'=>'CAT-F'],
            ['manufacturer'=>'ROBINSON','model'=>'R-66','icao_type_designator'=>'R66','icao_legacy_wtc'=>'L','recat_eu_wtc'=>'CAT-F'],
            ['manufacturer'=>'SCHWEIZER','model'=>'269D 330','icao_type_designator'=>'S330','icao_legacy_wtc'=>'L','recat_eu_wtc'=>'CAT-F'],
            ['manufacturer'=>'SIKORSKY','model'=>'CH-53A Sea Stallion','icao_type_designator'=>'H53','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-E'],
            ['manufacturer'=>'SIKORSKY','model'=>'CH-53K King Stallion','icao_type_designator'=>'H53S','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-E'],
            ['manufacturer'=>'SIKORSKY','model'=>'UH-60 Black Hawk','icao_type_designator'=>'H60','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-F'],
            ['manufacturer'=>'SIKORSKY','model'=>'S-51','icao_type_designator'=>'S51','icao_legacy_wtc'=>'L','recat_eu_wtc'=>'CAT-F'],
            ['manufacturer'=>'SIKORSKY','model'=>'S-52','icao_type_designator'=>'S52','icao_legacy_wtc'=>'L','recat_eu_wtc'=>'CAT-F'],
            ['manufacturer'=>'SIKORSKY','model'=>'S-55','icao_type_designator'=>'S55P','icao_legacy_wtc'=>'L','recat_eu_wtc'=>'CAT-F'],
            ['manufacturer'=>'SIKORSKY','model'=>'S-55T','icao_type_designator'=>'S55T','icao_legacy_wtc'=>'L','recat_eu_wtc'=>'CAT-F'],
            ['manufacturer'=>'SIKORSKY','model'=>'S-58','icao_type_designator'=>'S58P','icao_legacy_wtc'=>'L','recat_eu_wtc'=>'CAT-F'],
            ['manufacturer'=>'SIKORSKY','model'=>'S-58T','icao_type_designator'=>'S58T','icao_legacy_wtc'=>'L','recat_eu_wtc'=>'CAT-F'],
            ['manufacturer'=>'SIKORSKY','model'=>'Sea King','icao_type_designator'=>'S61','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-F'],
            ['manufacturer'=>'SIKORSKY','model'=>'HH-3 Pelican','icao_type_designator'=>'S61R','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-F'],
            ['manufacturer'=>'SIKORSKY','model'=>'HH-52 Seaguard','icao_type_designator'=>'S62','icao_legacy_wtc'=>'L','recat_eu_wtc'=>'CAT-F'],
            ['manufacturer'=>'SIKORSKY','model'=>'CH-54 Tarhe','icao_type_designator'=>'S64','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-E'],
            ['manufacturer'=>'SIKORSKY','model'=>'S-76','icao_type_designator'=>'S76','icao_legacy_wtc'=>'L','recat_eu_wtc'=>'CAT-F'],
            ['manufacturer'=>'SIKORSKY','model'=>'S-92 Helibus','icao_type_designator'=>'S92','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-F'],
            ['manufacturer'=>'SIKORSKY','model'=>'S-97 Raider','icao_type_designator'=>'S97','icao_legacy_wtc'=>'L','recat_eu_wtc'=>'CAT-F'],
            ['manufacturer'=>'SIKORSKY','model'=>'R-4 Hoverfly','icao_type_designator'=>'R4','icao_legacy_wtc'=>'L','recat_eu_wtc'=>'CAT-F'],
            ['manufacturer'=>'WESTLAND','model'=>'Lynx','icao_type_designator'=>'LYNX','icao_legacy_wtc'=>'L','recat_eu_wtc'=>'CAT-F'],
            ['manufacturer'=>'WESTLAND','model'=>'Scout','icao_type_designator'=>'SCOU','icao_legacy_wtc'=>'L','recat_eu_wtc'=>'CAT-F'],
            ['manufacturer'=>'WESTLAND','model'=>'Wasp','icao_type_designator'=>'WASP','icao_legacy_wtc'=>'L','recat_eu_wtc'=>'CAT-F'],
            ['manufacturer'=>'WESTLAND','model'=>'Wessex','icao_type_designator'=>'WESX','icao_legacy_wtc'=>'L','recat_eu_wtc'=>'CAT-F'],
            ['manufacturer'=>'EUROCOPTER','model'=>'AS-342 Gazelle','icao_type_designator'=>'GAZL','icao_legacy_wtc'=>'L','recat_eu_wtc'=>'CAT-F'],
            ['manufacturer'=>'EUROCOPTER','model'=>'AS-532AL Cougar','icao_type_designator'=>'AS32','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-F'],
            ['manufacturer'=>'ATLAS','model'=>'CSH-2 Rooivalk','icao_type_designator'=>'RVAL','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-F'],
            ['manufacturer'=>'BOEING','model'=>'MD-520N','icao_type_designator'=>'MD52','icao_legacy_wtc'=>'L','recat_eu_wtc'=>'CAT-F'],
            ['manufacturer'=>'BOEING','model'=>'MD-600N','icao_type_designator'=>'MD60','icao_legacy_wtc'=>'L','recat_eu_wtc'=>'CAT-F'],
            ['manufacturer'=>'MCDONNELL DOUGLAS','model'=>'MD-902 Explorer','icao_type_designator'=>'EXPL','icao_legacy_wtc'=>'L','recat_eu_wtc'=>'CAT-F'],
            ['manufacturer'=>'KAWASAKI','model'=>'OH-1','icao_type_designator'=>'OH1','icao_legacy_wtc'=>'L','recat_eu_wtc'=>'CAT-F'],
            ['manufacturer'=>'MITSUBISHI','model'=>'SH-60 Seahawk','icao_type_designator'=>'H60','icao_legacy_wtc'=>'M','recat_eu_wtc'=>'CAT-F'],
            ['manufacturer'=>'MITSUBISHI','model'=>'MH-2000','icao_type_designator'=>'MH20','icao_legacy_wtc'=>'L','recat_eu_wtc'=>'CAT-F'],
            ['manufacturer'=>'KOREA AEROSPACE','model'=>'Surion','icao_type_designator'=>'SURN','icao_legacy_wtc'=>'M','recat_eu_wtc'=>null],
            ['manufacturer'=>'VERTOL','model'=>'CH-21 Work horse','icao_type_designator'=>'H21','icao_legacy_wtc'=>'L','recat_eu_wtc'=>'CAT-F'],
        ];
    }
}
